/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLApplet;

import ContactList.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tejas
 */

public class CL_Applet extends java.applet.Applet {

    /**
     * Initializes the applet CL_Applet
     */
    String readf;
    static String writef;
    static ArrayList<Relative> ar = new ArrayList<Relative>();
    static ArrayList<PerFriend> apef = new ArrayList<PerFriend>();
    static ArrayList<ProFriend> aprf = new ArrayList<ProFriend>();
    static ArrayList<CasFriend> acf = new ArrayList<CasFriend>();
    GridBagLayout layout = new GridBagLayout();
    CreateAcq ca;
    DeleteAcq dea;
    DisplayAcq dia;
    DisplaySpeAcq dsa;
    SearchName sn;

    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    String s = "Display specific type\n     of Acquaintances";
                    jButton6.setText("<html>" + s.replaceAll("\\n", "<br>") + "</html>");
                    ca = new CreateAcq();
                    dea = new DeleteAcq();
                    dia = new DisplayAcq();
                    dsa = new DisplaySpeAcq();
                    sn = new SearchName();
                    GridBagConstraints gbc = new GridBagConstraints();
                    jPanel2.setLayout(layout);
                    gbc.gridx = 0;
                    gbc.gridy = 0;
                    jPanel2.add(ca);
                    gbc.gridx = 0;
                    gbc.gridy = 0;
                    jPanel2.add(dea);
                    gbc.gridx = 0;
                    gbc.gridy = 0;
                    jPanel2.add(dia);
                    gbc.gridx = 0;
                    gbc.gridy = 0;
                    jPanel2.add(dsa);
                    gbc.gridx = 0;
                    gbc.gridy = 0;
                    jPanel2.add(sn);
                    ca.setVisible(false);
                    dea.setVisible(false);
                    dia.setVisible(false);
                    dsa.setVisible(false);
                    sn.setVisible(false);

                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Enter file to Read data from :");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Data Read succeessfully from :");

        jLabel3.setText("Writing data to (Change below)  :");

        jButton3.setText("Create Acquaintance");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete Acquaintance");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Display all Acquaintances");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Display Specific type of Acquaintances");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Search for Name");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton8.setText("Exit Without Saving");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Save and Exit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel4.setText("Write data to :");

        jButton10.setText("OK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jButton1)))
                        .addGap(162, 162, 162)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton3)
                        .addGap(19, 19, 19)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(63, 63, 63)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here
            readf = jTextField1.getText();
            writef = readf;
            FileReader b1 = null;
            try {
                b1 = new FileReader(new File(readf + ".txt"));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CL_Applet.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedReader i1 = new BufferedReader(b1);
            String x;
            x = i1.readLine();
            //Reading data from the file
            while (true) {
                x = i1.readLine();
                if (x == null || x.isEmpty()) {
                    break;
                }
                if (x.split(":")[0].equalsIgnoreCase("RELATIVES")) {
                    do {
                        x = i1.readLine();
                        if (x == null || x.isEmpty()) {
                            break;
                        }
                        if (x.split(":")[0].split(" ")[0].equalsIgnoreCase("Relative")) {
                            Relative r = new Relative();
                            String[] s = (i1.readLine()).split(":");
                            r.name = s[1];
                            s = (i1.readLine()).split(":");
                            r.mobile = s[1];
                            s = (i1.readLine()).split(":");
                            r.email = s[1];
                            s = (i1.readLine()).split(":");
                            r.rbds = s[1];
                            s = (i1.readLine()).split(":");
                            r.rlms = s[1];
                            ar.add(r);
                        }
                    } while (true);
                } else if (x.split(":")[0].equalsIgnoreCase("PERSONAL FRIENDS")) {
                    do {
                        x = i1.readLine();
                        if (x == null || x.isEmpty()) {
                            break;
                        }
                        if (x.split(":")[0].split(" ")[0].equalsIgnoreCase("Personal")) {
                            PerFriend r = new PerFriend();
                            String[] s = i1.readLine().split(":");
                            r.name = s[1];
                            s = i1.readLine().split(":");
                            r.mobile = s[1];
                            s = i1.readLine().split(":");
                            r.email = s[1];
                            s = i1.readLine().split(":");
                            r.fc = s[1];
                            s = i1.readLine().split(":");
                            r.fms = s[1];
                            s = i1.readLine().split(":");
                            r.fde = s[1];
                            apef.add(r);
                        }
                    } while (true);
                } else if (x.split(":")[0].equalsIgnoreCase("PROFESSIONAL FRIENDS")) {
                    do {
                        x = i1.readLine();
                        if (x == null || x.isEmpty()) {
                            break;
                        }
                        if (x.split(":")[0].split(" ")[0].equalsIgnoreCase("Professional")) {
                            ProFriend r = new ProFriend();
                            String[] s = i1.readLine().split(":");
                            r.name = s[1];
                            s = i1.readLine().split(":");
                            r.mobile = s[1];
                            s = i1.readLine().split(":");
                            r.email = s[1];
                            s = i1.readLine().split(":");
                            r.pfci = s[1];
                            aprf.add(r);
                        }
                    } while (true);
                } else if (x.split(":")[0].equalsIgnoreCase("CASUAL FRIENDS")) {
                    do {
                        x = i1.readLine();
                        if (x == null || x.isEmpty()) {
                            break;
                        }
                        if (x.split(":")[0].split(" ")[0].equalsIgnoreCase("Casual")) {
                            CasFriend r = new CasFriend();
                            String[] s = i1.readLine().split(":");
                            r.name = s[1];
                            s = i1.readLine().split(":");
                            r.mobile = s[1];
                            s = i1.readLine().split(":");
                            r.email = s[1];
                            s = i1.readLine().split(":");
                            r.cfc = s[1];
                            s = i1.readLine().split(":");
                            r.cfwher = s[1];
                            s = i1.readLine().split(":");
                            r.cfms = s[1];
                            s = i1.readLine().split(":");
                            r.cfod = s[1];
                            acf.add(r);
                        }
                    } while (true);
                }
            }
            System.out.println(ar.size());
            jLabel2.setText("Data read succeessfully from " + readf + ".txt");
            jLabel3.setText("Writing Data to " + writef + ".txt (Click to change)");

        } catch (IOException ex) {
            Logger.getLogger(CL_Applet.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ca.setVisible(true);
        dea.setVisible(false);
        dia.setVisible(false);
        dsa.setVisible(false);
        sn.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ca.setVisible(false);
        dea.setVisible(true);
        dia.setVisible(false);
        dsa.setVisible(false);
        sn.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ca.setVisible(false);
        dea.setVisible(false);
        dia.setVisible(true);
        dsa.setVisible(false);
        sn.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ca.setVisible(false);
        dea.setVisible(false);
        dia.setVisible(false);
        dsa.setVisible(true);
        sn.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ca.setVisible(false);
        dea.setVisible(false);
        dia.setVisible(false);
        dsa.setVisible(false);
        sn.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        try {
            FileWriter b = null;
            b = new FileWriter(new File(writef + ".txt"));
            BufferedWriter i = new BufferedWriter(b);
            int k = 1;
            if (!ar.isEmpty()) {
                i.append(System.lineSeparator() + "RELATIVES:");
            }
            i.newLine();
            for (Relative c : ar) {
                i.append("Relative " + k + ":" + System.lineSeparator());
                i.append((c.toString()).replaceAll("\n", System.lineSeparator()));
                i.newLine();
                k++;
            }
            k = 1;
            if (!apef.isEmpty()) {
                i.append(System.lineSeparator() + "PERSONAL FRIENDS:");
            }
            i.newLine();
            for (PerFriend c : apef) {

                i.append("Personal Friend " + k + ":" + System.lineSeparator());
                i.append((c.toString()).replaceAll("\n", System.lineSeparator()));
                i.newLine();
                k++;
            }
            k = 1;
            if (!aprf.isEmpty()) {
                i.append(System.lineSeparator() + "PROFESSIONAL FRIENDS:");
            }
            i.newLine();
            for (ProFriend c : aprf) {

                i.append("Professional Friend " + k + ":" + System.lineSeparator());
                i.append((c.toString()).replaceAll("\n", System.lineSeparator()));
                i.newLine();
                k++;
            }
            k = 1;
            if (!acf.isEmpty()) {
                i.append(System.lineSeparator() + "CASUAL FRIENDS:");
            }
            i.newLine();
            for (CasFriend c : acf) {
                i.append("Casual Friend " + k + ":" + System.lineSeparator());
                i.append((c.toString()).replaceAll("\n", System.lineSeparator()));
                i.newLine();
                k++;
            }
            i.close();
            b.close();
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(CL_Applet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        writef = jTextField2.getText();

    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
