/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLApplet;

import ContactList.*;

/**
 *
 * @author tejas
 */
public class DisplayAcq extends javax.swing.JPanel {

    /**
     * Creates new form DisplayAcq
     */
    public DisplayAcq() {
        initComponents();
        jTextArea1.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("List of all Acquaintances : ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("DISPALY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jButton1)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StringBuilder s = new StringBuilder();
        if (CL_Applet.ar.size() != 0) {
            int i = 1;
            s.append("\nRELATIVES:");
            for (Relative a : CL_Applet.ar) {
                s.append("\nRelative " + i + ":");
                s.append("\n"+a);
                i++;
            }

        }
        if (CL_Applet.apef.size() != 0) {
            int i = 1;
            s.append("\n\nPERSONAL FRIENDS:");
            for (PerFriend a : CL_Applet.apef) {
                s.append("\nPersonal Friend " + i + ":");
                s.append("\n" + a);
                i++;
            }

        }
        if (CL_Applet.aprf.size() != 0) {
            int i = 1;
            s.append("\n\nPROFESSIONAL FRIENDS:");
            for (ProFriend a : CL_Applet.aprf) {
                s.append("\nProfessional Friend " + i + ":");
                s.append("\n" + a);
                i++;
            }

        }
        if (CL_Applet.acf.size() != 0) {
            int i = 1;
            s.append("\n\nCASUAL FRIENDS:");
            for (CasFriend a : CL_Applet.acf) {
                s.append("\nCasual Friend " + i + ":");
                s.append("\n" + a);
                i++;
            }

        }
       
        jTextArea1.setText(s.toString());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
